### ISSUE TITLE
stuck with "could not login with credentials"

### ISSUE THREAD

**Issue by mgalm** [bluecatlabs/rundeck-bluecat-gateway-plugin#4] opened 2018-12-21 10:27 UTC
Hi,

I saw the bash check and it always fails for me.
I struggled with something similar while creating a workaround to use cron on BAM.

I had to redirect it into a file to use the token from the file because the token would always be insert in a wrong manner.

`echo_time "Starting DIG Cron Workaround Script"
echo_time "+ Contacting DIG via URL \"$DIG_URL\" with User \"$DIG_USER\" to get Authentication Token"
AUTH=`$myCurl -s -k $DIG_URL/rest_login -F username=$DIG_USER -F password=$DIG_PASS`
TOKEN_OUT=`echo $AUTH | grep access_token | awk '{split($0,a,":"); print a[2]}' |tr -d '[:space:]'|tr -d '"'|tr -d }`
echo_time "++ Got Authentication Token: \"$TOKEN_OUT\""
echo_time "++ Preparing token for REST calls..."
TOKEN="Auth: Basic $TOKEN_OUT"
echo "-H \"$TOKEN\"" > $TOKEN_FILE
echo_time "++ Using Basic Authentication with String: \"$TOKEN\""
echo_time "+ Starting configured scripts: \"$SCRIPTS\""
for SCRIPT in $SCRIPTS
do
  echo_time "+++++++++++++++++++++++++++++++++++++++++++++++++"
  echo_time "+ Running script \"$SCRIPT\""
  CMD="$myCurl -s --config $TOKEN_FILE -X GET -k $DIG_URL/tag_ip4_networks/tag_ip4_networks_rest_endpoint?link_type=$SCRIPT"
  echo_time "++ Running command \"$CMD\""
  RETURN=`$CMD`
  STATUS=$?
  if [ $STATUS -ne 0 ]; then
        echo_time "++ Error during REST calls - Return code of script $SCRIPT was: $STATUS"
  fi
  echo_time "++ Feedback from workflow is:"
  echo_time "$RETURN"
done
echo_time "Finished DIG Cron Workaround Script"
`

Can you provide a working example?

**Comment by sharma-anshul** [comment] 2018-12-21 20:23
Hey @n3kgalm thanks for reporting these issues! We are a bit short on man power as most of the team is on vacation, but we'll be looking into them first thing as soon as people are back from the holidays. 
Please feel free to bring more things to our notice that don't work as intended if and when you run into them! Thanks again, and happy holidays!

**Comment by xiax** [comment] 2018-12-21 20:38
Hi @n3kgalm what version of the Gateway are you working with?

**Comment by mgalm** [comment] 2019-01-02 07:59
Gateway 18.12.1 with BAM 9.0.0

**Comment by xiax** [comment] 2019-01-02 16:21
Hi @n3kgalm, are you using the plugin with Rundeck and it isn't working? What is the error you get in the logs?

**Comment by mgalm** [comment] 2019-01-03 08:23
here is the result I'm getting with rundeck:

Could not login with credentials
Result: 1
Failed: NonZeroResultCode: Result code was 1

> gateway-rundeck Calls gateway endpoints
username: tag_worker
password: XXXXXXXX
URL: https://dig-01.lab.n3k.de
REST call: GET
Gateway Endpoint: api/v1/configurations/

**Comment by sharma-anshul** [comment] 2019-01-04 20:26
Hey @n3kgalm I was trying to reproduce the error and was wondering if you could confirm a couple of things:

1) Do you have https access set up for your gateway instance? 

2) Could you make sure that the `username` and `password` combination has login access to the running Gateway instance?

**Comment by mgalm** [comment] 2019-01-07 07:09
I'm doing rest request from the address manager with the same account using curl, which works.

**Comment by sharma-anshul** [comment] 2019-01-07 20:25
Hey @n3kgalm thanks for providing that information. Looking into it further, it seems that `curl` doesn't let you authenticate with self signed certificates. The reason why the curl command works while the plugin doesn't is because of the `-k` flag being passed into the curl command which skips checking the certificate. To circumnavigate this, there are a couple of options:

1. In the `URL` section in the Rundeck plugin, use `http` instead of `https`.

2. Obtain a certificate signed by one of the authorities included in the cURL `bundle` and setup Gateway to use that certificate instead.

**Comment by mgalm** [comment] 2019-01-08 08:05
ok, using http only seems to work for now.
At least I guess, I tried calling my custom rest workflow but it does give back:

{"code":404,"description":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.","status":"Not Found"}

Is there any documentation on how to call custom workflows (with their parameters)?
Everything I try seems to fail, or is it still an authentication issue?

**Comment by sharma-anshul** [comment] 2019-01-08 16:26
One of the reasons could be an issue with importing the workflow. Could you confirm that the workflow shows up in the `Workflow Permissions` tab under `Administration` and that the user you are using to access Gateway has valid permissions (correct UDF value(s)) to access the workflow? 

If you can't see the workflow in the list, you'd have to use the `Workflow Export/Import` tab to import it and then permission it using `Workflow Permissions`. (Additional information on importing and permissioning can be found in the `Help & Documentation` tab by clicking your username from Gateway or by referring to the Installation guide.)

In case you can see the workflow and it has the correct permissions set up, but you still can't access it would be great if you could share the error logs with us so that we can look into it further.

**Comment by sharma-anshul** [comment] 2019-01-11 20:16
Hey @n3kgalm just wanted to check in to see if the above comment helped and if we can close this issue. Thanks!

**Comment by sharma-anshul** [comment] 2019-01-21 18:16
Marking this issue closed.

**Closed as completed by sharma-anshul** 2019-01-21 18:16 UTC
